services:
    app.address_book_validator:
        class: AppBundle\Validaton\Constraints\AddressBookValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
        - { name: validator.constraint_validator, alias: address_book_validator }